FROM rust:slim

WORKDIR /src
COPY rust-toolchain.toml ./

RUN apt-get update && \
    apt-get install -y --no-install-recommends jq curl git && \
    rm -rf /var/lib/apt/lists/*

RUN rustup toolchain install --profile minimal --no-self-update

ENTRYPOINT ["cargo"]
CMD ["--help"]
